#!/usr/bin/env python
"""Python wrapper around jnml command"""

import os
import subprocess
import shutil
from xml.dom import minidom


def parse_arguments():
    """Parse command line arguments"""
    import argparse

    parser = argparse.ArgumentParser(description='Python wrapper of jnml')
    parser.add_argument('xml_filename', metavar='xmlfile', type=str,
                        help='The xml file to process')
    parser.add_argument('--sim', choices=('neuron', 'jlems'),
                        help='Simulator to use')
    parser.add_argument('--validate', action='store_true',
                        help='Only validate')
    parser.add_argument('--outputdir', nargs=1,
                        help='Directory to write output scripts to')

    return parser.parse_args()


def run_jnml(args):
    """Run the jnml command"""

    if args.outputdir:
        initialize_outputdir(args.outputdir[0], args.xml_filename)
        exec_dir = args.outputdir[0]
    else:
        exec_dir = "."

    if not args.sim:
        simulator_option = ''
    elif args.sim == 'jlems':
        simulator_option = ''
    else:
        simulator_option = '-%s' % args.sim

    script_dir = os.path.dirname(os.path.realpath(__file__))

    os.environ['JNML_HOME'] = script_dir

    execute_command_in_dir("%s/jnml %s %s" %
                          (script_dir, os.path.basename(args.xml_filename),
                              simulator_option), exec_dir)


def initialize_outputdir(output_dir, xml_filename):
    """Initialize the output directory"""
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    include_filenames = [xml_filename]

    for include_filename in include_filenames:
        xmldoc = minidom.parse(include_filename)
        includes = xmldoc.getElementsByTagName('Include')

        for include in includes:
            new_filename = os.path.join(
                os.path.dirname(include_filename),
                include.attributes['file'].value)
            include_filenames.append(new_filename)

    # TODO this doesn't work if you have xml files in subdirectory / abs paths

    for include_filename in include_filenames:
        shutil.copyfile(
            include_filename,
            os.path.join(
                output_dir,
                os.path.basename(include_filename))) 


def main():
    """Main"""

    args = parse_arguments()

    run_jnml(args)


def execute_command_in_dir(command, directory):
    """Execute a command in specific working directory"""
    if os.name == 'nt':
        directory = os.path.normpath(directory)
    print ">>>  Executing: (%s) in dir: %s" % (command, directory)
    return_string = subprocess.Popen(command, cwd=directory, shell=True,
                                     stdout=subprocess.PIPE).communicate()[0]
    return return_string


if __name__ == "__main__":
    main()
